<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Buku_tamu_model extends CI_Model
{

    public $table = 'buku_tamu';
    public $id = 'no_tamu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_tamu', $q);
        $this->db->or_like('tgl', $q);
	    $this->db->or_like('nama_tamu', $q);
	    $this->db->or_like('alamat', $q);
	    $this->db->or_like('tlp', $q);
	    $this->db->or_like('keperluan', $q);
        $this->db->or_like('keterangan', $q);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_tamu', $q);
        $this->db->or_like('tgl', $q);
	    $this->db->or_like('nama_tamu', $q);
	    $this->db->or_like('alamat', $q);
	    $this->db->or_like('tlp', $q);
	    $this->db->or_like('keperluan', $q);
        $this->db->or_like('keterangan', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Buku_tamu_model.php */
/* Location: ./application/models/Buku_tamu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-14 04:12:27 */
/* http://harviacode.com */